openapi: 3.2.0
info:
  title: Quadrant v2 alerts API
  description: The Quadrant API currently allows users to retrieve alert data by their client ID.
  contact:
    name: Quadrant Information Security
    url: https://www.quadrantsec.com/
    email: soc@quadrantsec.com
  version: 2.0.3
tags:
- name: v2 alerts
paths:
  /v2/alerts/{client_id}/:
    get:
      tags:
      - v2 alerts
      summary: Get Alerts
      operationId: get_alerts_v2_alerts__client_id___get
      security:
      - APIKeyHeader: []
      parameters:
      - name: client_id
        in: path
        required: true
        schema:
          type: string
          format: uuid
          title: Client Id
      - name: category
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/AlertCategory'
          default: escalated
      - name: size
        in: query
        required: false
        schema:
          type: integer
          maximum: 10000
          exclusiveMinimum: 0
          default: 10000
          title: Size
      - name: sort
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Sort
      - name: stream
        in: query
        required: false
        schema:
          type: boolean
          default: false
          title: Stream
      - name: next_page_token
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Next Page Token
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlertResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    GeoIPLocation:
      properties:
        city:
          type: string
          title: City
        country:
          type: string
          title: Country
        latitude:
          type: number
          title: Latitude
        longitude:
          type: number
          title: Longitude
        postal:
          type: string
          title: Postal
        subdivision:
          type: string
          title: Subdivision
        timezone:
          type: string
          title: Timezone
      type: object
      required:
      - city
      - country
      - latitude
      - longitude
      - postal
      - subdivision
      - timezone
      title: GeoIPLocation
    BluedotSrc:
      properties:
        api_user:
          type: string
          title: Api User
        category:
          type: string
          title: Category
        code:
          type: integer
          title: Code
        comments:
          type: string
          title: Comments
        counter:
          type: integer
          title: Counter
        ctime:
          type: string
          format: date-time
          title: Ctime
        ctime_epoch:
          type: integer
          title: Ctime Epoch
        last_seen:
          type: string
          format: date-time
          title: Last Seen
        mtime:
          type: string
          format: date-time
          title: Mtime
        mtime_epoch:
          type: integer
          title: Mtime Epoch
        query:
          type: string
          title: Query
        query_counter:
          type: integer
          title: Query Counter
        query_timestamp:
          type: string
          format: date-time
          title: Query Timestamp
        query_type:
          type: string
          title: Query Type
        source:
          type: string
          title: Source
      type: object
      required:
      - api_user
      - category
      - code
      - comments
      - counter
      - ctime
      - ctime_epoch
      - last_seen
      - mtime
      - mtime_epoch
      - query
      - query_counter
      - query_timestamp
      - query_type
      - source
      title: BluedotSrc
    NormalizationInfo:
      properties:
        src-ip:
          type: string
          title: Src-Ip
        src-port:
          type: string
          title: Src-Port
        username:
          type: string
          title: Username
      type: object
      required:
      - src-ip
      - src-port
      - username
      title: NormalizationInfo
    SuricataAlert:
      properties:
        alert:
          $ref: '#/components/schemas/AlertInfo'
        analyst:
          items:
            $ref: '#/components/schemas/AnalystResponse'
          type: array
          title: Analyst
        analyst_final_response:
          $ref: '#/components/schemas/AnalystResponse'
        auto_answer:
          type: string
          title: Auto Answer
        auto_answer_id:
          type: string
          title: Auto Answer Id
        auto_emailed:
          type: string
          title: Auto Emailed
        bluedot:
          $ref: '#/components/schemas/BluedotInfo'
        critical:
          type: string
          title: Critical
        cust_id:
          type: string
          title: Cust Id
        dest_dns:
          type: string
          title: Dest Dns
        dest_ip:
          type: string
          title: Dest Ip
        dest_port:
          type: string
          title: Dest Port
        emailed:
          type: string
          title: Emailed
        es_index:
          type: string
          title: Es Index
        event_type:
          type: string
          title: Event Type
        flow_id:
          type: string
          title: Flow Id
        geoip:
          $ref: '#/components/schemas/GeoIPInfo'
        geoip_dest:
          $ref: '#/components/schemas/GeoIPLocation'
        geoip_src:
          $ref: '#/components/schemas/GeoIPLocation'
        host:
          type: string
          title: Host
        in_iface:
          type: string
          title: In Iface
        proto:
          type: string
          title: Proto
        sensor_description:
          type: string
          title: Sensor Description
        snort_cid:
          type: string
          title: Snort Cid
        snort_id:
          type: string
          title: Snort Id
        snort_sid:
          type: string
          title: Snort Sid
        src_dns:
          type: string
          title: Src Dns
        src_ip:
          type: string
          title: Src Ip
        src_port:
          type: string
          title: Src Port
        timestamp:
          type: string
          format: date-time
          title: Timestamp
        flow:
          $ref: '#/components/schemas/FlowStats'
        packet:
          type: string
          title: Packet
        packet_info:
          $ref: '#/components/schemas/PacketInfo'
        sensor_type:
          type: string
          title: Sensor Type
          default: pie
        stream:
          type: integer
          title: Stream
      type: object
      required:
      - alert
      - analyst
      - analyst_final_response
      - auto_answer
      - auto_answer_id
      - auto_emailed
      - bluedot
      - critical
      - cust_id
      - dest_dns
      - dest_ip
      - dest_port
      - emailed
      - es_index
      - event_type
      - flow_id
      - geoip
      - geoip_dest
      - geoip_src
      - host
      - in_iface
      - proto
      - sensor_description
      - snort_cid
      - snort_id
      - snort_sid
      - src_dns
      - src_ip
      - src_port
      - timestamp
      - flow
      - packet
      - packet_info
      - stream
      title: SuricataAlert
    GeoIPInfo:
      properties:
        dest:
          $ref: '#/components/schemas/GeoIPLocation'
        src:
          $ref: '#/components/schemas/GeoIPLocation'
      type: object
      required:
      - dest
      - src
      title: GeoIPInfo
    AlertResponse:
      properties:
        total:
          type: integer
          title: Total
        page:
          $ref: '#/components/schemas/CurrentPageInfo'
        next:
          $ref: '#/components/schemas/NextPageInfo'
        category:
          $ref: '#/components/schemas/AlertCategory'
        filter:
          $ref: '#/components/schemas/HitFilter'
        sort:
          items:
            additionalProperties:
              $ref: '#/components/schemas/SortDirection'
            type: object
          type: array
          title: Sort
        alerts:
          items:
            anyOf:
            - $ref: '#/components/schemas/SaganAlert'
            - $ref: '#/components/schemas/SuricataAlert'
          type: array
          title: Alerts
      type: object
      required:
      - total
      - page
      - next
      - category
      - filter
      - sort
      - alerts
      title: AlertResponse
    SaganAlert:
      properties:
        alert:
          $ref: '#/components/schemas/AlertInfo'
        analyst:
          items:
            $ref: '#/components/schemas/AnalystResponse'
          type: array
          title: Analyst
        analyst_final_response:
          $ref: '#/components/schemas/AnalystResponse'
        auto_answer:
          type: string
          title: Auto Answer
        auto_answer_id:
          type: string
          title: Auto Answer Id
        auto_emailed:
          type: string
          title: Auto Emailed
        bluedot:
          $ref: '#/components/schemas/BluedotInfo'
        critical:
          type: string
          title: Critical
        cust_id:
          type: string
          title: Cust Id
        dest_dns:
          type: string
          title: Dest Dns
        dest_ip:
          type: string
          title: Dest Ip
        dest_port:
          type: string
          title: Dest Port
        emailed:
          type: string
          title: Emailed
        es_index:
          type: string
          title: Es Index
        event_type:
          type: string
          title: Event Type
        flow_id:
          type: string
          title: Flow Id
        geoip:
          $ref: '#/components/schemas/GeoIPInfo'
        geoip_dest:
          $ref: '#/components/schemas/GeoIPLocation'
        geoip_src:
          $ref: '#/components/schemas/GeoIPLocation'
        host:
          type: string
          title: Host
        in_iface:
          type: string
          title: In Iface
        proto:
          type: string
          title: Proto
        sensor_description:
          type: string
          title: Sensor Description
        snort_cid:
          type: string
          title: Snort Cid
        snort_id:
          type: string
          title: Snort Id
        snort_sid:
          type: string
          title: Snort Sid
        src_dns:
          type: string
          title: Src Dns
        src_ip:
          type: string
          title: Src Ip
        src_port:
          type: string
          title: Src Port
        timestamp:
          type: string
          format: date-time
          title: Timestamp
        facility:
          type: string
          title: Facility
        level:
          type: string
          title: Level
        normalize:
          $ref: '#/components/schemas/NormalizationInfo'
        payload:
          type: string
          title: Payload
        priority:
          type: string
          title: Priority
        program:
          type: string
          title: Program
        sensor_type:
          type: string
          title: Sensor Type
          default: lae
        stream:
          type: string
          title: Stream
        tag:
          type: string
          title: Tag
        xff:
          type: string
          title: Xff
      type: object
      required:
      - alert
      - analyst
      - analyst_final_response
      - auto_answer
      - auto_answer_id
      - auto_emailed
      - bluedot
      - critical
      - cust_id
      - dest_dns
      - dest_ip
      - dest_port
      - emailed
      - es_index
      - event_type
      - flow_id
      - geoip
      - geoip_dest
      - geoip_src
      - host
      - in_iface
      - proto
      - sensor_description
      - snort_cid
      - snort_id
      - snort_sid
      - src_dns
      - src_ip
      - src_port
      - timestamp
      - facility
      - level
      - normalize
      - payload
      - priority
      - program
      - stream
      - tag
      - xff
      title: SaganAlert
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    AlertInfo:
      properties:
        action:
          type: string
          title: Action
        category:
          type: string
          title: Category
        gid:
          type: integer
          title: Gid
        metadata:
          additionalProperties: true
          type: object
          title: Metadata
        rev:
          type: string
          title: Rev
        rule:
          type: string
          title: Rule
        severity:
          type: integer
          title: Severity
        signature:
          type: string
          title: Signature
        signature_id:
          type: string
          title: Signature Id
      type: object
      required:
      - action
      - category
      - gid
      - metadata
      - rev
      - rule
      - severity
      - signature
      - signature_id
      title: AlertInfo
    HitFilter:
      properties:
        terms:
          items:
            additionalProperties: true
            type: object
          type: array
          title: Terms
        ranges:
          items:
            additionalProperties:
              additionalProperties:
                anyOf:
                - type: string
                  format: date-time
                - type: integer
                - type: string
              propertyNames:
                $ref: '#/components/schemas/RangeQueryOperator'
              type: object
            type: object
          type: array
          title: Ranges
      type: object
      required:
      - terms
      - ranges
      title: HitFilter
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    RangeQueryOperator:
      type: string
      enum:
      - lt
      - gt
      - lte
      - gte
      title: RangeQueryOperator
    AnalystResponse:
      properties:
        critical:
          type: string
          title: Critical
        long_description:
          type: string
          title: Long Description
        name:
          type: string
          title: Name
        priority:
          type: integer
          title: Priority
        short_description:
          type: string
          title: Short Description
        short_description_id:
          type: integer
          title: Short Description Id
        timestamp:
          type: string
          format: date-time
          title: Timestamp
      type: object
      required:
      - critical
      - long_description
      - name
      - priority
      - short_description
      - short_description_id
      - timestamp
      title: AnalystResponse
    FlowStats:
      properties:
        bytes_toclient:
          type: string
          title: Bytes Toclient
        bytes_toserver:
          type: string
          title: Bytes Toserver
        pkts_toclient:
          type: string
          title: Pkts Toclient
        pkts_toserver:
          type: string
          title: Pkts Toserver
        start:
          type: string
          format: date-time
          title: Start
      type: object
      required:
      - bytes_toclient
      - bytes_toserver
      - pkts_toclient
      - pkts_toserver
      - start
      title: FlowStats
    PacketInfo:
      properties:
        linktype:
          type: integer
          title: Linktype
      type: object
      required:
      - linktype
      title: PacketInfo
    NextPageInfo:
      properties:
        url:
          anyOf:
          - type: string
          - type: 'null'
          title: Url
        expires_at:
          anyOf:
          - type: integer
          - type: 'null'
          title: Expires At
      type: object
      required:
      - url
      - expires_at
      title: NextPageInfo
    SortDirection:
      type: string
      enum:
      - asc
      - desc
      title: SortDirection
    AlertCategory:
      type: string
      enum:
      - reportable
      - benign
      - investigated
      - resolved
      - escalated
      - noncritical
      - critical
      title: AlertCategory
    BluedotInfo:
      properties:
        src:
          $ref: '#/components/schemas/BluedotSrc'
      type: object
      required:
      - src
      title: BluedotInfo
    CurrentPageInfo:
      properties:
        size:
          type: integer
          title: Size
        number:
          type: integer
          title: Number
      type: object
      required:
      - size
      - number
      title: CurrentPageInfo
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: API-Key
